
### Login API
POST http://localhost:3001/login/
Content-Type: application/json

 {
    "username": "rahul",
    "password": "rahul@2025"
 }

###
###
POST http://localhost:3001/login/
Content-Type: application/json

{
   "username": "shailu",
   "password": "shailu@2025"
}